version: "3"
services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///db.sqlite

  db:
    image: sqlite
    volumes:
      - db-data:/var/lib/sqlite
volumes:
  db-data: